### ISSUE TITLE
After last release TD-Agent doesn't work anymore

### ISSUE THREAD

**Issue by ruslan-belinskyy** [SumoLogic/fluentd-output-sumologic#62]
`Apr 27 13:04:06 systemd: Starting td-agent: Fluentd based data collector for Treasure Data...
Apr 27 13:04:06 fluentd: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/config/element.rb:221:in `unescape_parameter': undefined method `each_char' for nil:NilClass (NoMethodError)
Apr 27 13:04:06 fluentd: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/config/element.rb:204:in `dump_value'
Apr 27 13:04:06 fluentd: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/config/element.rb:151:in `block in to_s'
Apr 27 13:04:06 fluentd: from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/config/element.rb:150:in `each_pair'`

Issue here is that `custom_fields` value has null key

**Comment by frankreno** [comment]
Can you please share your configuration as well, feel free to redact the HTTP source url...

**Comment by ruslan-belinskyy** [comment]
This is gems we have:
```
td-agent-gem list | grep fluent
fluent-config-regexp-type (1.0.0)
fluent-logger (0.7.2)
fluent-plugin-elasticsearch (2.11.11)
fluent-plugin-kafka (0.7.9)
fluent-plugin-record-modifier (1.1.0)
fluent-plugin-rewrite-tag-filter (2.1.0)
fluent-plugin-s3 (1.1.6)
fluent-plugin-td (1.0.0)
fluent-plugin-td-monitoring (0.2.4)
fluent-plugin-webhdfs (1.2.3)
fluentd (1.2.6)
```

**Comment by ruslan-belinskyy** [comment]
```
<source>
  @type tail
  format json
  path /var/lib/docker/containers/*/*.log
  pos_file /tmp/applog.log.pos
  tag box35ee1
  read_from_head false
  time_format %iso8601
</source>

<source>
  @type tail
  format none
  path /tmp/bootstrap.log
  pos_file /tmp/app-bootstrap-log.log.pos
  tag box35ee1
  read_from_head false
  time_format %iso8601
</source>

<filter **.api>
  @type grep
  <exclude>
    key log
    pattern Varnish\/fastly \(healthcheck\)|\[DEBUG\] Application started \[usfp\:none\]|ELB\-HealthChecker\/1\.0
  </exclude>
</filter>

<filter **.api>
  @type record_transformer
  <record>
    aws_cluster_code api
    aws_environment_code stg
    aws_hostname_suffix ccc
    aws_instance_configuration_name release-9
    local box1
  </record>
</filter>

<match **.api>
  @type sumologic
  endpoint https://collectors.sumologic.com/receiver/v1/http/BBB
  source_category ecomm
  source_name ecomm
  open_timeout 10
    proxy_uri http://proxy.com:80
  </match>

<match **.bootstrap>
  @type sumologic
  endpoint https://collectors.sumologic.com/receiver/v1/http/AAA
  source_category ecomm
  source_name ecomm
  open_timeout 10
    proxy_uri http://proxy.com:80
  </match>
```
